@echo off
setlocal EnableExtensions DisableDelayedExpansion

set "ROOT_DIR=%~dp0"
if "%ROOT_DIR:~-1%"=="\" set "ROOT_DIR=%ROOT_DIR:~0,-1%"

set "APP_DIR=%ROOT_DIR%\aiplayground-portal"
set "NODE_DIR=D:\soft\node-v22.18.0-win-x64"
set "NODE_EXE=%NODE_DIR%\node.exe"
set "NPM_CMD=%NODE_DIR%\npm.cmd"
set "NPX_CMD=%NODE_DIR%\npx.cmd"
set "PYTHON_DIR=D:\soft\python-3.11.9-embed-amd64"
set "PYTHON_EXE=%PYTHON_DIR%\python.exe"

set "POSTGRES_HOST=localhost"
set "POSTGRES_PORT=5432"
set "POSTGRES_DB=aiplayground"
set "POSTGRES_USER=aiplayground"
set "POSTGRES_PASSWORD=aiplayground"
set "DATABASE_URL=postgresql://%POSTGRES_USER%:%POSTGRES_PASSWORD%@%POSTGRES_HOST%:%POSTGRES_PORT%/%POSTGRES_DB%"
set "PORT=5013"
set "NEXTAUTH_URL=http://localhost:%PORT%/aiplayground"
set "NEXT_PUBLIC_BASE_PATH=/aiplayground"

set "ENV_FILE=%APP_DIR%\.env"
set "ENV_TMP=%ENV_FILE%.tmp"
set "SEED_DB=1"
set "DRY_RUN=0"
set "EXIT_CODE=0"

:parse_args
if "%~1"=="" goto after_args
if /I "%~1"=="--no-seed" (
  set "SEED_DB=0"
  shift
  goto parse_args
)
if /I "%~1"=="--seed" (
  set "SEED_DB=1"
  shift
  goto parse_args
)
if /I "%~1"=="--dry-run" (
  set "DRY_RUN=1"
  shift
  goto parse_args
)
if /I "%~1"=="--help" goto usage
echo [ERROR] Unknown argument: %~1
goto usage

:after_args
if not exist "%APP_DIR%\package.json" (
  echo [ERROR] App directory not found: %APP_DIR%
  exit /b 1
)
if not exist "%NODE_EXE%" (
  echo [ERROR] Node executable not found: %NODE_EXE%
  exit /b 1
)
if not exist "%NPM_CMD%" (
  echo [ERROR] npm.cmd not found: %NPM_CMD%
  exit /b 1
)
if not exist "%NPX_CMD%" (
  echo [ERROR] npx.cmd not found: %NPX_CMD%
  exit /b 1
)

set "PATH=%NODE_DIR%;%PATH%"
if exist "%PYTHON_EXE%" (
  set "PATH=%PYTHON_DIR%;%PATH%"
  set "npm_config_python=%PYTHON_EXE%"
)

call :load_nextauth_secret
if not defined NEXTAUTH_SECRET call :set_default_nextauth_secret
if not defined NEXTAUTH_SECRET (
  echo [ERROR] Unable to determine NEXTAUTH_SECRET.
  exit /b 1
)

if "%DRY_RUN%"=="1" (
  echo [DRY-RUN] Would write environment file: %ENV_FILE%
) else (
  call :write_env_file
  if errorlevel 1 exit /b %ERRORLEVEL%
)

pushd "%APP_DIR%" >nul
if errorlevel 1 (
  echo [ERROR] Unable to open app directory: %APP_DIR%
  exit /b 1
)

if not exist "node_modules" (
  echo [INFO] Installing npm dependencies
  if "%DRY_RUN%"=="1" (
    echo [DRY-RUN] "%NPM_CMD%" install
  ) else (
    call "%NPM_CMD%" install
    if errorlevel 1 (
      set "EXIT_CODE=%ERRORLEVEL%"
      echo [ERROR] Installing npm dependencies failed with exit code %EXIT_CODE%.
      goto finish
    )
  )
) else (
  echo [INFO] Reusing existing node_modules.
)

echo [INFO] Pushing Prisma schema to PostgreSQL
if "%DRY_RUN%"=="1" (
  echo [DRY-RUN] "%NPX_CMD%" prisma db push
) else (
  call "%NPX_CMD%" prisma db push
  if errorlevel 1 (
    set "EXIT_CODE=%ERRORLEVEL%"
    echo [ERROR] Pushing Prisma schema to PostgreSQL failed with exit code %EXIT_CODE%.
    goto finish
  )
)

if "%SEED_DB%"=="1" (
  echo [INFO] Seeding database
  if "%DRY_RUN%"=="1" (
    echo [DRY-RUN] "%NPM_CMD%" run db:seed
  ) else (
    call "%NPM_CMD%" run db:seed
    if errorlevel 1 (
      set "EXIT_CODE=%ERRORLEVEL%"
      echo [ERROR] Seeding database failed with exit code %EXIT_CODE%.
      goto finish
    )
  )
) else (
  echo [INFO] Skipping database seed.
)

echo [INFO] Starting development server at %NEXTAUTH_URL%
if "%DRY_RUN%"=="1" (
  echo [DRY-RUN] Would run: "%NPX_CMD%" next dev -p %PORT%
  set "EXIT_CODE=0"
) else (
  call "%NPX_CMD%" next dev -p %PORT%
  set "EXIT_CODE=%ERRORLEVEL%"
)

:finish
popd >nul
exit /b %EXIT_CODE%

:write_env_file
(
  echo # Auto-generated by run-aiplayground.bat
  echo POSTGRES_HOST=%POSTGRES_HOST%
  echo POSTGRES_PORT=%POSTGRES_PORT%
  echo POSTGRES_DB=%POSTGRES_DB%
  echo POSTGRES_USER=%POSTGRES_USER%
  echo POSTGRES_PASSWORD=%POSTGRES_PASSWORD%
  echo DATABASE_URL=%DATABASE_URL%
  echo.
  echo # NextAuth
  echo NEXTAUTH_URL=%NEXTAUTH_URL%
  echo NEXTAUTH_SECRET=%NEXTAUTH_SECRET%
  echo.
  echo # App
  echo PORT=%PORT%
  echo NEXT_PUBLIC_BASE_PATH=%NEXT_PUBLIC_BASE_PATH%
) > "%ENV_TMP%"
if errorlevel 1 (
  echo [ERROR] Failed to write temporary env file: %ENV_TMP%
  exit /b 1
)
move /Y "%ENV_TMP%" "%ENV_FILE%" >nul
if errorlevel 1 (
  echo [ERROR] Failed to update env file: %ENV_FILE%
  exit /b 1
)
echo [INFO] Wrote environment file: %ENV_FILE%
exit /b 0

:load_nextauth_secret
if not exist "%ENV_FILE%" exit /b 0
for /f "usebackq tokens=1,* delims==" %%A in ("%ENV_FILE%") do (
  if /I "%%~A"=="NEXTAUTH_SECRET" (
    if not "%%~B"=="" set "NEXTAUTH_SECRET=%%~B"
  )
)
if defined NEXTAUTH_SECRET echo [INFO] Reusing NEXTAUTH_SECRET from existing .env
exit /b 0

:set_default_nextauth_secret
set "NEXTAUTH_SECRET=local-dev-secret-change-me"
echo [WARN] Using the default NEXTAUTH_SECRET. Replace it in %ENV_FILE% if you need a stable custom value.
exit /b 0

:usage
echo Usage: %~n0 [--dry-run] [--seed ^| --no-seed]
echo.
echo   --dry-run   Show the steps without writing files, installing packages, or starting the app.
echo   --seed      Run Prisma seed after db push. This is the default.
echo   --no-seed   Skip Prisma seed.
exit /b 1
